#!/bin/sh

if [ -b /dev/mmcblk0p3 ] ; then
    DATAPARTITION=/dev/mmcblk0p3
else
    DATAPARTITION=/dev/sda2
fi

if [ ! -d /data ] ; then
    mkdir /data
fi

# Mount /data automatically on next startups
sed -i 's@^\(.*/data.*\)noauto\(.*\)@\1defaults\2@' /etc/fstab

echo -n "Trying to mount /data... "
mount /data >> /dev/null 2>&1
if [ $? -eq 0 ] ; then
    echo "done"
    exit 0
else
    echo "failed. Creating partition."
fi

echo -n "Creating vfat partition in /dev/sda2... "
mkfs.vfat -n VETERODATA "$DATAPARTITION" >> /dev/null 2>&1
if [ $? -eq 0 ] ; then
    echo "done"
else
    echo "failed. Opening debug shell."
    /bin/sh
    exit 0
fi

echo -n "Mounting /data... "
mount /data >> /dev/null 2>&1
if [ $? -eq 0 ] ; then
    echo "done"
    exit 0
else
    echo "failed"
    exit 1
fi
