#!/bin/sh

SSH_KEYS=/data/ssh_keys
ROOT_HOME=`grep '^root:' /etc/passwd | cut -d : -f 6`
ROOT_SSH_DIR=$ROOT_HOME/.ssh
AUTHORIZED_KEYS=$ROOT_SSH_DIR/authorized_keys

if [ -r "$SSH_KEYS" ] ; then
    echo "SSH keys found. Adding to authorized_keys and disabling password root access"
    if ! [ -d "$ROOT_SSH_DIR" ] ; then
        mkdir "$ROOT_SSH_DIR"
        chmod 0700 "$ROOT_SSH_DIR"
    fi
    cat "$SSH_KEYS" >> "$AUTHORIZED_KEYS"
fi

NETWORK_INTERFACES=/data/network_interfaces

if [ -r "$NETWORK_INTERFACES" ] ; then
    echo "Custom network configuration found. Copying to /etc"
    cp "$NETWORK_INTERFACES" /etc/network/interfaces
fi

NETWORK_RESOLV_CONF=/data/network_resolv_conf

if [ -r "$NETWORK_RESOLV_CONF" ] ; then
    echo "Custom resolver configuration found. Copying to /etc"
    cp "$NETWORK_RESOLV_CONF" /etc/resolv.conf
fi
