#
# Simple development makefile
#

#
# add more flags here,
# but don't remove the "+="
#
CFLAGS += -O2 -g -Wall #-Wsign-compare -Wfloat-equal -Wformat-security #-Werror
CPPFLAGS +=
LDFLAGS +=


all:
	@echo "Nothing to do"

install:
	install -m0755 init $(DESTDIR)/init


.PHONY: all install clean

# end of development makefile
